// Shared styles used across all admin tab components

export const S = {
  card: {
    background: "#fff",
    borderRadius: 12,
    boxShadow: "0 2px 12px rgba(128,0,0,0.08)",
    padding: 28,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 16,
    borderBottom: "2px solid #f0d0d0",
  },
  title: {
    fontSize: 28,
    fontWeight: 800,
    color: "#800000",
    margin: 0,
  },
  addBtn: {
    background: "#800000",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "10px 20px",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
  },
  searchBar: {
    background: "#fff5f5",
    border: "1px solid #f0d0d0",
    borderRadius: 10,
    padding: "14px 18px",
    marginBottom: 20,
    display: "flex",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
  },
  input: {
    border: "1px solid #ddd",
    borderRadius: 6,
    padding: "8px 12px",
    fontSize: 14,
    outline: "none",
    flex: 1,
    minWidth: 200,
  },
  select: {
    border: "1px solid #ddd",
    borderRadius: 6,
    padding: "8px 12px",
    fontSize: 14,
    outline: "none",
    background: "#fff",
    cursor: "pointer",
    minWidth: 160,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    background: "#800000",
    color: "#fff",
    padding: "12px 16px",
    textAlign: "left",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
  },
  td: {
    padding: "14px 16px",
    borderBottom: "1px solid #f5e8e8",
    fontSize: 14,
    color: "#333",
  },
  tdAlt: {
    padding: "14px 16px",
    borderBottom: "1px solid #f5e8e8",
    fontSize: 14,
    color: "#333",
    background: "#fff9f9",
  },
  editBtn: {
    background: "#800000",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "6px 14px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    marginRight: 6,
  },
  deleteBtn: {
    background: "#6b0000",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "6px 14px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  badge: (color = "#800000") => ({
    display: "inline-block",
    padding: "3px 12px",
    borderRadius: 20,
    border: `1px solid ${color}`,
    color: color,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.5,
  }),
  showingBar: {
    background: "#fff5f5",
    border: "1px solid #f0d0d0",
    borderRadius: "0 0 8px 8px",
    padding: "10px 16px",
    textAlign: "center",
    fontSize: 13,
    color: "#800000",
    fontWeight: 600,
  },
  modal: {
    position: "fixed",
    top: 0, left: 0, right: 0, bottom: 0,
    background: "rgba(0,0,0,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalBox: {
    background: "#fff",
    borderRadius: 12,
    padding: 32,
    width: "100%",
    maxWidth: 500,
    boxShadow: "0 8px 40px rgba(128,0,0,0.2)",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: "#800000",
    marginBottom: 20,
  },
  formGroup: {
    marginBottom: 16,
  },
  label: {
    display: "block",
    fontSize: 13,
    fontWeight: 600,
    color: "#555",
    marginBottom: 6,
  },
  formInput: {
    width: "100%",
    border: "1px solid #ddd",
    borderRadius: 6,
    padding: "9px 12px",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
  },
  formSelect: {
    width: "100%",
    border: "1px solid #ddd",
    borderRadius: 6,
    padding: "9px 12px",
    fontSize: 14,
    outline: "none",
    background: "#fff",
    boxSizing: "border-box",
  },
  modalActions: {
    display: "flex",
    gap: 10,
    marginTop: 24,
    justifyContent: "flex-end",
  },
  cancelBtn: {
    background: "#f5f5f5",
    color: "#555",
    border: "1px solid #ddd",
    borderRadius: 6,
    padding: "9px 20px",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
  },
  saveBtn: {
    background: "#800000",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "9px 24px",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
  },
};

export const API = "http://localhost:5000/api";
export const getHeaders = () => {
  const token = localStorage.getItem("token");
  return { Authorization: `Bearer ${token}`, "Content-Type": "application/json" };
};